"""StarBreaker runtime package.

Phase 7 migration complete. The original ``_legacy.py`` monolith has been
decomposed into themed submodules; this ``__init__`` re-exports the
stable public surface consumed by ``ui.py`` and tests.
"""

from __future__ import annotations

from .constants import (
    DECAL_OFFSET_EXTERNAL_DEFAULT,
    DECAL_OFFSET_INTERNAL_DEFAULT,
    DECAL_OFFSET_MODIFIER_NAME,
    GLTF_LIGHT_BASIS_CORRECTION,
    GLTF_PBR_WATTS_TO_LUMENS,
    LIGHT_CANDELA_TO_WATT,
    LIGHT_VISUAL_GAIN,
    MATERIAL_IDENTITY_SCHEMA,
    NON_COLOR_INPUT_KEYWORDS,
    PACKAGE_ROOT_PREFIX,
    POM_DETAIL_DEFAULT,
    POM_DETAIL_ITEMS,
    PROP_ENGINE_GLOW_CONTROL_JSON,
    PROP_ENGINE_GLOW_STRENGTH,
    PROP_SHARED_GLOW_CONTROL_JSON,
    PROP_SHARED_GLOW_STRENGTH,
    PROP_ENTITY_NAME,
    PROP_DECAL_OFFSET_EXTERNAL,
    PROP_DECAL_OFFSET_INTERNAL,
    PROP_EXPORT_ROOT,
    PROP_IMPORTED_SLOT_MAP,
    PROP_IMPORTED_SLOT_NAMES,
    PROP_INSTANCE_JSON,
    PROP_MATERIAL_IDENTITY,
    PROP_MATERIAL_SIDECAR,
    PROP_MESH_ASSET,
    PROP_MISSING_ASSET,
    PROP_PACKAGE_NAME,
    PROP_PACKAGE_ROOT,
    PROP_PAINT_VARIANT_SIDECAR,
    PROP_PALETTE_ID,
    PROP_PALETTE_SCOPE,
    PROP_SCENE_PATH,
    PROP_SHADER_FAMILY,
    PROP_SOURCE_NODE_NAME,
    PROP_SUBMATERIAL_JSON,
    PROP_SURFACE_SHADER_MODE,
    PROP_TEMPLATE_KEY,
    PROP_TEMPLATE_PATH,
    PROP_HAS_POM,
    PROP_LIGHT_ACTIVE_STATE,
    PROP_LIGHT_SEMANTIC_KIND,
    PROP_LIGHT_STATES_JSON,
    SCENE_POM_DETAIL_PROP,
    SCENE_AXIS_CONVERSION,
    SCENE_AXIS_CONVERSION_INV,
    SCENE_ENGINE_GLOW_PROP,
    SCENE_SHARED_GLOW_PROP,
    SCENE_WEAR_STRENGTH_PROP,
    SURFACE_SHADER_MODE_GLASS,
    SURFACE_SHADER_MODE_PRINCIPLED,
    TEMPLATE_COLLECTION_NAME,
    pom_detail_settings,
)
from .importer import PackageImporter
from .importer.groups import apply_pom_detail_mode
from .package_ops import (
    apply_decal_offsets_to_package_root,
    animation_overlap_warnings,
    apply_animation_mode_to_package_root,
    apply_engine_glow_to_package_root,
    apply_shared_glow_to_package_root,
    apply_light_state,
    apply_livery_to_package_root,
    apply_livery_to_selected_package,
    apply_paint_to_package_root,
    apply_paint_to_selected_package,
    apply_palette_to_package_root,
    apply_palette_to_selected_package,
    package_animation_diagnostics,
    available_package_animation_items,
    available_package_animation_names,
    available_light_state_names,
    engine_glow_control_enabled,
    engine_glow_strength,
    shared_glow_control_enabled,
    shared_glow_strength,
    decal_offset_control_enabled,
    delete_animation_instance,
    dirty_package_material_objects,
    dump_selected_metadata,
    exterior_palette_ids,
    find_package_root,
    import_package,
    MaterialRefreshSession,
    package_root_needs_material_refresh,
    refresh_materials_for_package_root,
    resolve_package_scene_path,
    insert_animation_clip_at_frame,
    package_animation_instances,
    package_animation_mode_map,
    set_animation_instance_muted,
    solo_animation_instance,
    update_animation_instance_start_frame,
)
